### ISSUE TITLE
Mismatch of data for some locations

### ISSUE THREAD

**Issue by pramodG44** [pxthxk/COVIDBedsIndia#12]
Hi, I have been using your API for a project and i have noticed for some location the data doesn't match with the data displayed on their official sites.
Here i have given West Bengal data, If you check the official site, the numbers are different.

![image](https://user-images.githubusercontent.com/54209582/121151021-a5901c00-c861-11eb-9f98-44623e42bc3a.png)

The same data is coming for last couple of days as well. 
are the scrappers for some sites not working?

**Comment by Souravgithub1999** [comment]
I am also facing the same issue. Now the API is not working. Do you find any alternative API?
