### ISSUE TITLE
URGENT: Tamilnadu API not working

### ISSUE THREAD

**Issue by JustTheCoolest** [pxthxk/COVIDBedsIndia#13]
The API for Tamilnadu has only been returning an empty list. Issue first noticed on the morning of June 18.

Even on covidbedsindia.in itself, the map hasn't been showing any hospitals in Tamilnadu since this issue

The source website (https://stopcorona.tn.gov.in/beds.php) is working perfectly though

**Comment by pxthxk** [comment]
Has been fixed, thank you!
